# Generated by Django 4.2.3 on 2023-07-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsverse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weatherinfo',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eventsverse_app.eventslist'),
        ),
    ]
