# Generated by Django 4.2.3 on 2023-07-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsverse_app', '0002_weatherinfo_id_alter_weatherinfo_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFlights',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_airport', models.CharField(max_length=3)),
                ('event_airport', models.CharField(max_length=3)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsverse_app.eventslist')),
            ],
        ),
        migrations.RemoveField(
            model_name='weatherinfo',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='weatherinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='weatherinfo',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eventsverse_app.eventslist'),
        ),
        migrations.DeleteModel(
            name='AvaliableFlights',
        ),
    ]
