# Generated by Django 4.2.3 on 2023-07-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsverse_app', '0004_eventslist_id_alter_eventslist_event_id'),
    ]

    operations = [
    migrations.RemoveField(
        model_name='availableflights',
        name='event_id',
    ),
]

